spring.application.name=Affitti
spring.datasource.url=jdbc:postgresql://localhost:5432/affitti_db
spring.datasource.username=postgres
spring.datasource.password=admin

spring.datasource.driver-class-name=org.postgresql.Driver

# Forza il dialetto PostgreSQL per JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
